### ISSUE TITLE
Modal Grid...

### ISSUE THREAD

**Issue by paperboyo** [guardian/media-atom-maker#118]
...won't launch in Firefox 50 on OSX 10.9.5 (yes, I'm logged in):
`Load denied by X-Frame-Options: https://composer.[DOMAIN]/ does not permit framing by https://media-atom[ETC.].`

Plus, a thing that bugs me in Composer as well... Maybe Grid should disallow or warn about using poster images of ratio that is different to the ratio of the video file (16:9 most of the time, but with these facebookie ones, I don't know any more). Otherwise people just use Landscape (5:3) and stuff jumps around like in: https://www.theguardian.com/us-news/video/2016/dec/01/protesters-north-carolina-keith-scott-police-shooting-video.

**Comment by clloyd** [comment]
Thanks @paperboyo! Will look into it

**Comment by paperboyo** [comment]
Main issue seems fixed, closing. The tiny difference between 16:9 and 15:9 (5:3) OTOH will keep biting us in the ass forever most probably...
