### ISSUE TITLE
File naming convention

### ISSUE THREAD

**Issue by fredex42** [guardian/media-atom-maker#264]
Hi all,

As i discussed with @mbarton,  we should enforce the standard naming convention when uploading files.

This is: YYMMDDfileNameWithNoSpacesOrWeirdStuff.ext

**Comment by akash1810** [comment]
what's the benefit of this vs a GUID?

**Comment by mbarton** [comment]
As an extension to @akash1810, what does Pluto use the naming convention for? As opposed to the information encoded in the project name, master name etc

**Comment by akash1810** [comment]
Closing as we're using GUIDs for filenames in MAM.
