### ISSUE TITLE
Configure monetisation of videos

### ISSUE THREAD

**Issue by mbarton** [guardian/media-atom-maker#338]
Videos uploaded through the tool or the CDS routes do not have monetisation enabled (the $ sign in the YouTube admin UI).

**Comment by mbarton** [comment]
http://stackoverflow.com/questions/18800665/how-to-enable-monetization-for-videos-uploaded-with-youtube-data-api-v3

**Comment by akash1810** [comment]
YouTube's docs - https://developers.google.com/youtube/partner/upload_claim_sample

**Comment by mbarton** [comment]
Fixed by #399
